apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: temp 
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: index
        configMap:
          name: my-index
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index 
          mountPath: /usr/share/nginx/html/
